server:
  port: 8080

spring:
  mvc:
    servlet:
      load-on-startup: 1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://112.74.43.76:3306/gmall?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root

logging:
  level:
    com.agolike: debug
  path: "D:/test/test.log"
  pattern:
    dateformat: "''"
mybatis:
  type-aliases-package: com.agolike.gmall.user.bean
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
