
spring:
  dubbo:
    application:
      name: manage-service
    registry:
      address: 112.74.43.76:2181
      protocol: zookeeper
    base-package: com.agolike.gmall
    protocol:
      name: dubbo
  mvc:
    servlet:
      load-on-startup: 1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://112.74.43.76/gmall?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root

logging:
  level:
    com.agolike: debug
  path: "D:/test/test.log"
  pattern:
    dateformat: "''"
mybatis:
  type-aliases-package: com.agolike.gmall.user.bean
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8092